"""NetGuard AI — Alert model.

Stores security alerts raised by the threat-detection engine.
"""

from __future__ import annotations

import enum
from datetime import datetime
from typing import Dict, Any

from app.extensions import db


class SeverityLevel(enum.Enum):
    """Alert severity levels."""

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class Alert(db.Model):  # type: ignore[name-defined]
    """Represents a security alert generated by the threat-detection engine."""

    __tablename__ = "alerts"

    id: int = db.Column(db.Integer, primary_key=True, autoincrement=True)
    timestamp: datetime = db.Column(db.DateTime, nullable=False, index=True)
    threat_type: str = db.Column(db.String(50), nullable=False, index=True)
    severity: str = db.Column(db.Enum(SeverityLevel), nullable=False, index=True)
    source_ip: str = db.Column(db.String(45), nullable=False, index=True)
    destination_ip: str = db.Column(db.String(45), nullable=False)
    description: str = db.Column(db.Text, nullable=False)
    raw_evidence: str | None = db.Column(db.Text, nullable=True)
    recommended_action: str = db.Column(db.Text, nullable=False)
    is_resolved: bool = db.Column(db.Boolean, default=False)
    resolved_at: datetime | None = db.Column(db.DateTime, nullable=True)
    resolved_by: str | None = db.Column(db.String(100), nullable=True)
    created_at: datetime = db.Column(db.DateTime, default=datetime.utcnow)

    # ── Serialisation ─────────────────────────────────────────────────

    def to_dict(self) -> Dict[str, Any]:
        """Return a JSON-serialisable dictionary of this alert."""
        return {
            "id": self.id,
            "timestamp": self.timestamp.isoformat() if self.timestamp else None,
            "threat_type": self.threat_type,
            "severity": self.severity.value if isinstance(self.severity, SeverityLevel) else self.severity,
            "source_ip": self.source_ip,
            "destination_ip": self.destination_ip,
            "description": self.description,
            "raw_evidence": self.raw_evidence,
            "recommended_action": self.recommended_action,
            "is_resolved": self.is_resolved,
            "resolved_at": self.resolved_at.isoformat() if self.resolved_at else None,
            "resolved_by": self.resolved_by,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }

    def __repr__(self) -> str:
        return f"<Alert {self.id} [{self.severity}] {self.threat_type} from {self.source_ip}>"
