"""Initial migration

Revision ID: 615f5040ee9e
Revises: 
Create Date: 2026-06-10 19:53:50.504717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '615f5040ee9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('context_used', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_conversations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_conversations_session_id'), ['session_id'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('threat_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severitylevel'), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=False),
    sa.Column('destination_ip', sa.String(length=45), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('raw_evidence', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_source_ip'), ['source_ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_threat_type'), ['threat_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_timestamp'), ['timestamp'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('device_type', sa.String(length=30), nullable=False, comment='router | switch | server | pc | iot | firewall | unknown'),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('vendor', sa.String(length=100), nullable=True),
    sa.Column('os_guess', sa.String(length=100), nullable=True),
    sa.Column('health_status', sa.Enum('HEALTHY', 'WARNING', 'CRITICAL', 'UNKNOWN', name='healthstatus'), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_ip_address'), ['ip_address'], unique=True)

    op.create_table('geo_traffic',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('country_name', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('packet_count', sa.Integer(), nullable=True),
    sa.Column('total_bytes', sa.BigInteger(), nullable=True),
    sa.Column('reputation_score', sa.Float(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('geo_traffic', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_geo_traffic_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_geo_traffic_ip_address'), ['ip_address'], unique=False)

    op.create_table('health_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('traffic_stability', sa.Float(), nullable=False),
    sa.Column('device_availability', sa.Float(), nullable=False),
    sa.Column('alert_frequency', sa.Float(), nullable=False),
    sa.Column('bandwidth_usage', sa.Float(), nullable=False),
    sa.Column('packet_loss', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('EXCELLENT', 'GOOD', 'WARNING', 'CRITICAL', name='networkstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('health_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_scores_created_at'), ['created_at'], unique=False)

    op.create_table('ml_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('algorithm', sa.String(length=100), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('model_path', sa.String(length=500), nullable=False),
    sa.Column('trained_at', sa.DateTime(), nullable=False),
    sa.Column('training_samples', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name')
    )
    op.create_table('ml_predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('prediction_type', sa.String(length=50), nullable=False),
    sa.Column('prediction_data', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('prediction_for', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_predictions_model_name'), ['model_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_predictions_prediction_type'), ['prediction_type'], unique=False)

    op.create_table('packets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('src_ip', sa.String(length=45), nullable=False),
    sa.Column('dst_ip', sa.String(length=45), nullable=False),
    sa.Column('src_port', sa.Integer(), nullable=True),
    sa.Column('dst_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=20), nullable=False),
    sa.Column('packet_size', sa.Integer(), nullable=False),
    sa.Column('ttl', sa.Integer(), nullable=True),
    sa.Column('src_mac', sa.String(length=17), nullable=True),
    sa.Column('dst_mac', sa.String(length=17), nullable=True),
    sa.Column('payload_preview', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('packets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_packets_dst_ip'), ['dst_ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_packets_protocol'), ['protocol'], unique=False)
        batch_op.create_index(batch_op.f('ix_packets_src_ip'), ['src_ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_packets_timestamp'), ['timestamp'], unique=False)

    op.create_table('simulation_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_type', sa.String(length=50), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('alerts_generated', sa.JSON(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulation_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulation_results_scenario_type'), ['scenario_type'], unique=False)

    op.create_table('device_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_device_id', sa.Integer(), nullable=False),
    sa.Column('target_device_id', sa.Integer(), nullable=False),
    sa.Column('packet_count', sa.Integer(), nullable=True),
    sa.Column('total_bytes', sa.BigInteger(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['target_device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_links_source_device_id'), ['source_device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_links_target_device_id'), ['target_device_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_links_target_device_id'))
        batch_op.drop_index(batch_op.f('ix_device_links_source_device_id'))

    op.drop_table('device_links')
    with op.batch_alter_table('simulation_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulation_results_scenario_type'))

    op.drop_table('simulation_results')
    with op.batch_alter_table('packets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_packets_timestamp'))
        batch_op.drop_index(batch_op.f('ix_packets_src_ip'))
        batch_op.drop_index(batch_op.f('ix_packets_protocol'))
        batch_op.drop_index(batch_op.f('ix_packets_dst_ip'))

    op.drop_table('packets')
    with op.batch_alter_table('ml_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_predictions_prediction_type'))
        batch_op.drop_index(batch_op.f('ix_ml_predictions_model_name'))

    op.drop_table('ml_predictions')
    op.drop_table('ml_models')
    with op.batch_alter_table('health_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_scores_created_at'))

    op.drop_table('health_scores')
    with op.batch_alter_table('geo_traffic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_geo_traffic_ip_address'))
        batch_op.drop_index(batch_op.f('ix_geo_traffic_country_code'))

    op.drop_table('geo_traffic')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_ip_address'))

    op.drop_table('devices')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_timestamp'))
        batch_op.drop_index(batch_op.f('ix_alerts_threat_type'))
        batch_op.drop_index(batch_op.f('ix_alerts_source_ip'))
        batch_op.drop_index(batch_op.f('ix_alerts_severity'))

    op.drop_table('alerts')
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_conversations_session_id'))
        batch_op.drop_index(batch_op.f('ix_ai_conversations_created_at'))

    op.drop_table('ai_conversations')
    # ### end Alembic commands ###
